server:
  port: 8849

spring:
  profiles:
    active: native
  application:
    name: config
  cloud:
    config:
      server:
        native:
          searchLocations: classpath:config

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8848/eureka/

