server:
  port: 8008

spring:
  application:
    name: gateway
  cloud:
    gateway:
      x-forwarded:
        enabled: true
        host-enabled: true
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
          filters:
            - PreserveHostHeader
            - StripPrefix=1

eureka:
  client:
    serviceUrl:
      defaultZone: http://register-server:8848/eureka/
