server:
  port: 6513

logging:
  level:
    root: INFO
    org.springframework.web: DEBUG
    org.springframework.security: DEBUG
    org.springframework.security.oauth2: DEBUG
#    org.springframework.boot.autoconfigure: DEBUG

eureka:
  client:
    serviceUrl:
      defaultZone: http://register-server:8848/eureka/

spring:
  application:
    name: upms
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://auth-server:6628/oauth2/jwks

mybatis-plus:
  mapper-locations: classpath:/mapper/*Mapper.xml
  global-config:
    banner: false
    db-config:
      table-underline: true
  configuration:
    cache-enabled: false
    map-underscore-to-camel-case: true
    default-enum-type-handler: com.baomidou.mybatisplus.extension.handlers.MybatisEnumTypeHandler
