server:
  port: 8848

spring:
  application:
    name: eureka

eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://register-server:8848/eureka/
  server:
    waitTimeInMsWhenSyncEmpty: 0
