server:
  port: 6628

spring:
  thymeleaf:
    cache: false
  application:
    name: auth
  security:
    oauth2:
      authorization:
        client:
          - client-id: mall
            client-secret: secret
            redirect-uri: http://localhost:8008/mall/login/oauth2/code/mall
            scope:
              - mall:read
              - mall:write
          - client-id: admin
            client-secret: secret
            redirect-uri: http://localhost:6222/login/oauth2/code/admin
      client:
        registration:
          github:
            client-id: xxxx
            client-secret: xxxx
          gitee:
            client-id: xxxx
            client-secret: xxxx
            authorization-grant-type: authorization_code
            redirect-uri: https://xxx/login/oauth2/code/gitee
          wechat:
            client-id: xxx
            client-secret: xxxx
            authorization-grant-type: authorization_code
            redirect-uri: https://xxx/login/oauth2/code/wx
            scope: snsapi_login
            client-authentication-method: post
          qq:
            client-id: xxx
            client-secret: xxxx
            authorization-grant-type: authorization_code
            redirect-uri: https://xxx/login/oauth2/code/qq
            scope: get_user_info
            client-authentication-method: post
        provider:
          gitee:
            authorization-uri: https://gitee.com/oauth/authorize
            token-uri: https://gitee.com/oauth/token
            user-info-uri: https://gitee.com/api/v5/user
          wechat:
            authorization-uri: https://open.weixin.qq.com/connect/qrconnect
            token-uri: https://api.weixin.qq.com/sns/oauth2/access_token
            user-info-uri: https://api.weixin.qq.com/sns/userinfo
            user-info-authentication-method: form
          qq:
            authorization-uri: https://graph.qq.com/oauth2.0/authorize
            token-uri: https://graph.qq.com/oauth2.0/token
            user-info-uri: https://graph.qq.com/oauth2.0/me
            user-info-authentication-method: form

eureka:
  client:
    serviceUrl:
      defaultZone: http://register-server:8848/eureka/

logging:
  level:
    root: INFO
    org.springframework.web: DEBUG
    org.springframework.security: DEBUG
    org.springframework.security.oauth2: DEBUG
#    org.springframework.boot.autoconfigure: DEBUG

temp:
  redirect_uri: http://localhost:8008/mall/login/oauth2/code/mall
