server:
  port: 6110

spring:
  application:
    name: auth

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://register-server:8848/eureka/

logging:
  level:
    root: INFO
    org.springframework.web: INFO
    org.springframework.security: INFO
    org.springframework.security.oauth2: DEBUG
#    org.springframework.boot.autoconfigure: DEBUG

temp:
  redirect_uri: http://localhost:8800/login/oauth2/code/mall
