server:
  port: 8800

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://register-server:8848/eureka/

logging:
  level:
    root: INFO
    org.springframework.web: INFO
    org.springframework.security: DEBUG
    org.springframework.security.oauth2: DEBUG
#    org.springframework.boot.autoconfigure: DEBUG

spring:
  security:
    oauth2:
      client:
        registration:
          mall:
            provider: mall
            client-id: mall
            client-secret: secret
            authorization-grant-type: authorization_code
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
            scope: mall.read,mall.write
        provider:
          mall:
            authorization-uri: http://auth.flizi.cn:6628/oauth2/authorize
            token-uri: http://auth.flizi.cn:6628/oauth2/token
            user-info-uri: http://localhost:6513/user_info
            user-name-attribute: name
  application:
    name: mall
